#!/bin/sh

WALLPAPER='/usr/share/wallpapers/aptosid-nemesis-wide.png'
[ -f "${WALLPAPER}" ] || exit 0

for loop in 1 2 3 4 5 6 7 8 9 10; do
	WORKSPACE=$(xfconf-query --channel xfce4-desktop --list | awk '/last-image$/{ print }')
	for ws in ${WORKSPACE}; do
		xfconf-query --create --channel xfce4-desktop \
			--property "${ws}" --type string --set "${WALLPAPER}"
	done
	[ -n "${WORKSPACE}" ] && break || sleep 1
done
