#!/bin/sh

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xfce4-screensaver \
	--property /lock/enabled --type bool \
	--set false

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xfce4-screensaver \
	--property /lock/sleep-activation --type bool \
	--set false

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xfce4-power-manager \
	--property /xfce4-power-manager/show-tray-icon --type bool \
	--set true

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xfce4-power-manager \
	--property /xfce4-power-manager/presentation-mode --type bool \
	--set true

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xfce4-power-manager \
	--property /xfce4-power-manager/lock-screen-suspend-hibernate \
	--type bool --set false

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xfce4-session \
	--property /general/SaveOnExit --type bool --set false

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xfce4-session \
	--property /general/AutoSave --type bool --set false

cp /usr/share/aptosid-settings-xfce/*.desktop /etc/xdg/autostart/
