#!/bin/sh

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xfce4-screensaver \
	--property /lock/enabled --type bool \
	--set false

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xfce4-screensaver \
	--property /lock/sleep-activation --type bool \
	--set false

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xfce4-power-manager \
	--property /xfce4-power-manager/show-tray-icon --type bool \
	--set true

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xfce4-power-manager \
	--property /xfce4-power-manager/presentation-mode --type bool \
	--set true

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xfce4-power-manager \
	--property /xfce4-power-manager/lock-screen-suspend-hibernate \
	--type bool --set false

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xfce4-session \
	--property /general/SaveOnExit --type bool --set false

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xfce4-session \
	--property /general/AutoSave --type bool --set false

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xsettings \
	--property /Net/IconThemeName --type string --set 'Mint-Y-Blue'

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xsettings \
	--property /Net/ThemeName --type string --set 'Arc-Dark'

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xsettings \
	--property /Net/FontName --type string --set 'Noto Sans 11'

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xsettings \
	--property /Net/MonospaceFontName --type string --set 'Noto Mono 11'

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xsettings \
	--property /Gtk/CursorThemeName --type string --set 'Bibata-Modern-Ice'

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xfce4-panel \
	--property /plugins/plugin-12/digital-layout --type int --set 3

sudo -u "${FLL_LIVE_USER}" dbus-run-session -- xfconf-query \
	--create --channel xfce4-panel \
	--property /plugins/plugin-12/digital-time-font --type string \
	--set 'Noto Sans 11'
