theme.palette.semantic_migrated = 1
theme.mode.light.token.mirc_0 = d3d3 d7d7 cfcf
theme.mode.light.token.mirc_1 = 2e2e 3434 3636
theme.mode.light.token.mirc_2 = 3434 6565 a4a4
theme.mode.light.token.mirc_3 = 4e4e 9a9a 0606
theme.mode.light.token.mirc_4 = cccc 0000 0000
theme.mode.light.token.mirc_5 = 8f8f 3939 0202
theme.mode.light.token.mirc_6 = 5c5c 3535 6666
theme.mode.light.token.mirc_7 = cece 5c5c 0000
theme.mode.light.token.mirc_8 = c4c4 a0a0 0000
theme.mode.light.token.mirc_9 = 7373 d2d2 1616
theme.mode.light.token.mirc_10 = 1111 a8a8 7979
theme.mode.light.token.mirc_11 = 5858 a1a1 9d9d
theme.mode.light.token.mirc_12 = 5757 7979 9e9e
theme.mode.light.token.mirc_13 = a0d0 42d4 6562
theme.mode.light.token.mirc_14 = 5555 5757 5353
theme.mode.light.token.mirc_15 = 8888 8a8a 8585
theme.mode.light.token.mirc_16 = d3d3 d7d7 cfcf
theme.mode.light.token.mirc_17 = 2e2e 3434 3636
theme.mode.light.token.mirc_18 = 3434 6565 a4a4
theme.mode.light.token.mirc_19 = 4e4e 9a9a 0606
theme.mode.light.token.mirc_20 = cccc 0000 0000
theme.mode.light.token.mirc_21 = 8f8f 3939 0202
theme.mode.light.token.mirc_22 = 5c5c 3535 6666
theme.mode.light.token.mirc_23 = cece 5c5c 0000
theme.mode.light.token.mirc_24 = c4c4 a0a0 0000
theme.mode.light.token.mirc_25 = 7373 d2d2 1616
theme.mode.light.token.mirc_26 = 1111 a8a8 7979
theme.mode.light.token.mirc_27 = 5858 a1a1 9d9d
theme.mode.light.token.mirc_28 = 5757 7979 9e9e
theme.mode.light.token.mirc_29 = a0d0 42d4 6562
theme.mode.light.token.mirc_30 = 5555 5757 5353
theme.mode.light.token.mirc_31 = 8888 8a8a 8585
theme.mode.light.token.selection_foreground = d3d3 d7d7 cfcf
theme.mode.light.token.selection_background = 2020 4a4a 8787
theme.mode.light.token.text_foreground = eeee eeee ecec
theme.mode.light.token.text_background = 3535 3535 3535
theme.mode.light.token.marker = 8f8f 3939 0202
theme.mode.light.token.tab_new_data = 3434 6565 a4a4
theme.mode.light.token.tab_highlight = 4e4e 9a9a 0606
theme.mode.light.token.tab_new_message = cece 5c5c 0000
theme.mode.light.token.tab_away = 8888 8a8a 8585
theme.mode.light.token.spell = a4a4 0000 0000
